### ISSUE TITLE
Add support for login inside docker 

### ISSUE THREAD

**Issue by tonsquemike** [ml2grow/GAEPyPI#2]
Hi, I try to upload my python library using GAEPyPI in a continuous integration pipeline. The deploy is made inside a docker image. When the pipeline comes to "deploy with GAEPyPI" show this: 
```
Writing TABICON-1.0/setup.cfg
Creating tar archive
removing 'TABICON-1.0' (and everything under it)
running upload
/usr/local/lib/python2.7/getpass.py:83: GetPassWarning: Can not control echo on the terminal.
  passwd = fallback_getpass(prompt, stream)
Warning: Password input may be echoed.
Password: Traceback (most recent call last):
  File "setup.py", line 10, in <module>
    packages=['TABICON']
  File "/usr/local/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/local/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/distutils/command/upload.py", line 60, in run
    self.upload_file(command, pyversion, filename)
  File "/usr/local/lib/python2.7/distutils/command/upload.py", line 135, in upload_file
    self.password)
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

**Comment by javdrher** [comment]
Hi @tonsquemike , 

my apologies for the late response, I do not seem to get notifications from this repository. The issue happens on your side, so I'm first going to need information on how to replicate this issue as I have never encountered it before (though we also deploy in CI running in a docker container). What version of setuptools do you have installed on your CI?

**Comment by tonsquemike** [comment]
Hi @javdrher , I forgot to close this issue.

The error was my fault, I forgot to add my $user and $password as environment variables in Gitlab.
